# Generated by Django 4.2 on 2023-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_login_email_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='selectclass',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Attendance',
            field=models.CharField(default='default_Attendance', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='DateTime',
            field=models.CharField(default='default_DateTime', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='RollNumber',
            field=models.CharField(default='default_RollNumber', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='StudentName',
            field=models.CharField(default='default_StudentName', max_length=100),
        ),
    ]
