# Generated by Django 4.2 on 2023-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_remove_attendance_selectclass_attendance_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='SelectClass',
            field=models.CharField(default='default_RollNumber', max_length=20),
        ),
    ]
